### ISSUE TITLE
Which ckpt should I load to evaluate the model on NYUv2?

### ISSUE THREAD

**Issue by Bearick** [cake-lab/HybridDepth#2]
Hi @AshkanGanj 
I want to evaluate your model on NYUv2 to see if the reported metrics in the paper are solid. Which ckpt should I use, Hybrid-Depth-NYU-5 or Hybrid-Depth-NYU-10 ?

**Comment by AshkanGanj** [comment]
Hello @Bearick 

After following the instructions and downloading all the necessary files, including DFF-DFV.tar, you can run the evaluation with `Hybrid-Depth-NYU-10` on the NYU dataset. Please use the linked instructions to download the full version of the NYU dataset (not the labeled version). After running the evaluation, you can view the results by opening the notebook `notebooks/analysis.ipynb` and analyzing the evaluation results we used in the paper.

FYI: Please pull the latest code, as I have added a new key to the NYU config (`n_stack`) to control the number of focal stacks. Now you can change the number of images in focal stack by adjusting this parameter.
