### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by thanhdat77** [cake-lab/HybridDepth#3]
I looked inside your `'setup.py'` and your '`environment.yml`' noticed that the opencv-python library is missing.
In your `'depthNet.py'`, I found that you are using absolute paths. I’ve changed all of them, but I still can't run the code.
![image](https://github.com/user-attachments/assets/dc49b220-a692-40d0-b2c1-ff217cc73e70)

![image](https://github.com/user-attachments/assets/7ab0dac7-1c48-4bd0-92fd-9ee44933784a)

Can you point out where i can fix it

**Comment by AshkanGanj** [comment]
Hi, 
The path is just a placeholder. You should change them based on your needs. Try this `checkpoints/DFF-DFV.tar`. Also, if you are using Google Colab, it is possible that it is causing problems. The provided code and files has been tested, so the  problem might be from your path, or google colab.

**Comment by kagevazquez** [comment]
Have you thought of making a huggingface space? The people need a taste

**Comment by AshkanGanj** [comment]
> Have you thought of making a huggingface space? The people need a taste

@kagevazquez Yes, we're planning to publish a Hugging Face Space soon! In the meantime, we've shared all the necessary codes and files to make everything easily accessible.

**Comment by thanhdat77** [comment]
Hi @kagevazquez,

I tried running it locally and adjusted the path, but I’m still encountering the same issue. I also noticed that when I use `os.environ["CUDA_VISIBLE_DEVICES"] = "2"`, it causes CUDA to become unavailable.

For more context, I'm using WSL with PyTorch 2.1.0 and CUDA 11.8. 

Thank you for your contribution to this project. I'm excited to see how it evolves and to test your code on Hugging Face

**Comment by AshkanGanj** [comment]
@thanhdat77 
About the `os.environ["CUDA_VISIBLE_DEVICES"] = "2". Thanks for catching it. This one is for multi-GPU training when you want to select a specific GPU to train or evaluate. I pushed a bug fix for removing this; it should fix your problem right now. 
Regrading your error, how about you use absoulute paths?

**Comment by AshkanGanj** [comment]
I am closing this issue. Since I assume the problem has been solved.
