### ISSUE TITLE
The pre-trained file provided has many key values that cannot correspond to the model

### ISSUE THREAD

**Issue by Good-Dish** [cake-lab/HybridDepth#4]
Hello. The pre-trained file provided has many key values that cannot correspond to the model. 
I want to ask if there are specific requirements for the backbone version of each component within the DepthNetModule() model.
Thank you.
![屏幕截图 2024-08-28 204113](https://github.com/user-attachments/assets/885fcd89-c29b-4dd1-b2dd-a977c5992507)

**Comment by AshkanGanj** [comment]
Hello @Good-Dish 
Thanks for your interest in our work. Yes, our model is built based on Python lightning, so `torch.load()` may not work. I pushed a bug fix for `test.ipynb` and right now everything should work as intended with the provided checkpoints. Please pull the latest version or update the model loading script cell as below: 
``` Python
# Load the model checkpoint
model_path = 'checkpoints/NYUBestScaleInv10Full.ckpt'
model = DepthNetModule.load_from_checkpoint(model_path)
model.eval()
model = model.to('cuda')
```

**Comment by Good-Dish** [comment]
Thanks
