### ISSUE TITLE
great work but the usage instructions are poor

### ISSUE THREAD

**Issue by ah3243** [cake-lab/HybridDepth#9]
Amazing research but as with many projects the usage instructions are poor and hard to use, which will really limit the impact of the work outside a citation and possible use by other researchers. Just adding a google colab notebook that just works without needing to download work around conda environments etc. I really would make a big difference. Currently you have to really invest time cobbling together the different parts to get a basic local inference demo working.

**Comment by AshkanGanj** [comment]
Hi, 
I am working on publishing the version 2 of HybridDepth with improved performance and easier instructions. I will try to add a torchhub model to make it easier for inference.

**Comment by AshkanGanj** [comment]
HybridDepth is now available on torch.hub and I also added a new colab for running a basic inference. 
 Colab notebook : https://colab.research.google.com/github/cake-lab/HybridDepth/blob/main/notebooks/starterColab.ipynb
